### ISSUE TITLE
customAction & sayFeedback

### ISSUE THREAD

**Issue by ssosas** [linto-ai/linto-web-client#1]
Hi all,
I've a question regarding functions fired when the skill returns a JSON containing customAction & say objects... On my client, I observe only the function related to customAction is fired, I would like to fire at the same time the sayFeedback, is it possible? or do i need to implement the 'await linto.say(...)' also in the customAction function?

Many thanks!

Sergio

**Comment by damienlaine** [comment]
https://github.com/linto-ai/linto-web-client/blob/master/src/handlers/linto.js Line 21

`export async function nlpAnswer(event) {
    if (event.detail.behavior.customAction) {
        this.dispatchEvent(new CustomEvent("custom_action_from_skill", {
            detail: event.detail
        }))
        return // Might handle custom_action say or ask, so we just exit here.
    }

    if (event.detail.behavior.say) {
        this.dispatchEvent(new CustomEvent("say_feedback_from_skill", {
            detail: event.detail
        }))
        return
    }

    if (event.detail.behavior.ask) {
        this.dispatchEvent(new CustomEvent("ask_feedback_from_skill", {
            detail: event.detail
        }))
    }
}`

As stated, i leave the handler as soon as the custom_action_from skill is fired, This design lets you handle say or ask within the customAction function itself. As proposed, you shall make the customAction function async and await the embedded linto.say promise to fullfil.

This is by design as you might not want to always trigger linto.say when using a custom action. You can change this by removing the return statement on line 26 and re-compile the lib.
